"""Build source-screening/control artifacts, not a scientific solver.

No model equation is discretized or numerical validation performed here.
"""
from pathlib import Path
import json, csv, hashlib, platform, shutil, zipfile
from importlib.metadata import version, PackageNotFoundError
from openpyxl import Workbook, load_workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.worksheet.table import Table, TableStyleInfo

ROOT = Path('/home/user')
REVIEW = ROOT / 'PRE_EXECUTION_REVIEW'
DATE = '2026-09-30'

refs = [
 {'id':'B01','authors':'Huang, Yan, Wu, Yu','year':'2025','title':'New insights on generalized heat conduction and thermoelastic coupling models','journal':'Applied Mathematics and Mechanics (English Edition)','doi':'10.1007/s10483-025-3280-7','source':'https://link.springer.com/article/10.1007/s10483-025-3280-7','role':'Recent-model/source-case verification candidate','source_level':'Metadata + abstract/preview; full equations/BCs unread','configuration':'1D slim-strip thermal shock, as stated in abstract','full_source':'NOT_OBTAINED','reconstruction':'BLOCKED — full model/case required','reference_data':'Unknown beyond preview; no curves digitized','project_comparison':'NOT_RUN','claim_boundary':'Cannot infer exact operators, coefficient restrictions or common limits from model names','next_requirement':'Legitimate full text; equations, BCs/ICs, material table, output definitions and admissibility'},
 {'id':'B02','authors':'Bagri, Eslami','year':'2007','title':'A unified generalized thermoelasticity; solution for cylinders and spheres','journal':'International Journal of Mechanical Sciences','doi':'10.1016/j.ijmecsci.2007.04.004','source':'https://www.sciencedirect.com/science/article/abs/pii/S0020740307000665','role':'Coupled LS/GL/GN common-limit verification candidate','source_level':'Publisher metadata/abstract/introduction preview','configuration':'Homogeneous-isotropic hollow cylinder/sphere thermal shock; exact source case not reconstructed','full_source':'NOT_OBTAINED','reconstruction':'BLOCKED — full source case required','reference_data':'Full parameters/curves unavailable in current attempt','project_comparison':'NOT_RUN','claim_boundary':'Finite cylinder is not an infinite cavity; theoretical agreement is not physical validation','next_requirement':'Full case/equations/BCs/ICs and explicit reduction from the selected recent model'},
 {'id':'B03','authors':'Gordeliy, Crouch, Mogilevskaya','year':'2008','title':'Transient heat conduction in a medium with two circular cavities: Semi-analytical solution','journal':'International Journal of Heat and Mass Transfer','doi':'10.1016/j.ijheatmasstransfer.2007.10.021','source':'https://www.sciencedirect.com/science/article/abs/pii/S0017931007006618','role':'Heat-only classical cavity verification candidate','source_level':'Metadata/abstract/introduction/selected preview','configuration':'Infinite medium, two circular cavities, suddenly applied steady Dirichlet conditions','full_source':'NOT_OBTAINED','reconstruction':'BLOCKED — coefficients/settings/reference case required','reference_data':'Full series, numerical settings and examples not reconstructed','project_comparison':'NOT_RUN','claim_boundary':'Not a coupled stress case or the same loading as a finite heat-flux pulse','next_requirement':'Full text or an independently derived and clearly labelled analytical control; document case mapping'},
 {'id':'B04','authors':'Klimm, Amgalan, Ganschow, Kwasniewski, Galazka, Bickermann','year':'2023 issue / 2022 online','title':'The Thermal Conductivity Tensor of beta-Ga2O3 from 300 to 1275 K','journal':'Crystal Research and Technology','doi':'10.1002/crat.202200204','source':'https://d-nb.info/1274779782/34','role':'Experimental material characterization / parameter provenance','source_level':'Full 5-page PDF read; tensor/coordinate/method equations; rendered pages 2–3','configuration':'Laser flash on nominally undoped crystal slices; diffusivity fitted, conductivity derived using density/database cp','full_source':'MAIN_PDF_OBTAINED; SUPPLEMENT_NOT_OBTAINED','reconstruction':'SOURCE_INSPECTION_COMPLETED; experiment not reconstructed','reference_data':'300 K source tensor + main plotted curves; Tables S1/S2 and detector Figure S3 unread','project_comparison':'NOT_RUN','claim_boundary':'Measured/derived conductivity inputs do not independently validate new non-Fourier transient stresses','next_requirement':'Supplement, uncertainty/measurement-model details and full coupled/dynamic parameters before a matched comparison'},
 {'id':'B05','authors':'Jiang, Qian, Li, Yang','year':'2018','title':'Three-dimensional anisotropic thermal conductivity tensor of single crystalline beta-Ga2O3','journal':'Applied Physics Letters','doi':'10.1063/1.5054573','source':'https://pubs.aip.org/aip/apl/article/113/23/232105/36409/Three-dimensional-anisotropic-thermal-conductivity','role':'Additional experimental property reference — correction required','source_level':'Publisher metadata/correction link + indexed abstract/method excerpts; not full original audit','configuration':'Elliptical-beam TDTR tensor characterization; different coordinate convention from B04','full_source':'Original full article not audited','reconstruction':'HELD — corrected version/frame must be checked','reference_data':'No numerical corrected-data import performed','project_comparison':'NOT_RUN','claim_boundary':'Do not copy uncorrected Eq4 or treat different sample/frame results as interchangeable','next_requirement':'Read original + B06; define a consistent orthonormal frame and measurement scope'},
 {'id':'B06','authors':'Jiang, Qian, Li, Yang','year':'2019','title':'Erratum to Three-dimensional anisotropic thermal conductivity tensor of single crystalline beta-Ga2O3','journal':'Applied Physics Letters','doi':'10.1063/1.5088513','source':'https://pubs.aip.org/aip/apl/article/114/4/049902/1022980/Erratum-Three-dimensional-anisotropic-thermal','role':'Source correction / origin integrity','source_level':'Publisher correction metadata/main text; Eq4 sign and interpretation inspected','configuration':'Correction to B05 tensor sign/heat-flux interpretation and Fig2b','full_source':'CORRECTION_TEXT_INSPECTED','reconstruction':'Correction existence/content verified; matrix import/rotation not executed','reference_data':'No corrected numerical matrix certified for project use','project_comparison':'NOT_RUN','claim_boundary':'Correction is not a new experiment or completed project validation','next_requirement':'Propagate correction in any future input import; preserve both version identities'}
]
journals = [
 {'journal':'Applied Mathematics and Mechanics (English Edition)','print_issn':'0253-4827','eissn':'1573-2754','quartile_database':'SCImago/SJR (Scopus-based)','reporting_year':2025,'category':'Applied Mathematics; Mechanical Engineering; Mechanics of Materials','quartile':'Q1 in listed categories','checked_date':DATE,'quartile_source':'https://www.scimagojr.com/journalsearch.php?q=25178&tip=sid','scie_evidence':'Publisher indexing list: SCIE + Scopus','index_source':'https://link.springer.com/journal/10483','independent_mjl':'NOT_CHECKED','jcr_quartile':'NOT_DIRECTLY_VERIFIED','fit':'Preliminary: mechanics/mathematical modelling; exact model source B01','final_journal':'NOT_SELECTED','full_policy_review':'PENDING: full article/data/code/AI/length/publication-model review'},
 {'journal':'International Journal of Heat and Mass Transfer','print_issn':'0017-9310','eissn':'1879-2189','quartile_database':'SCImago/SJR (Scopus-based)','reporting_year':2025,'category':'Fluid Flow and Transfer Processes; Mechanical Engineering; Condensed Matter Physics','quartile':'Q1 in listed categories','checked_date':DATE,'quartile_source':'https://www.scimagojr.com/journalsearch.php?q=20448&tip=sid','scie_evidence':'Publisher indexing list: SCIE + Scopus','index_source':'https://www.sciencedirect.com/journal/international-journal-of-heat-and-mass-transfer/about/insights','independent_mjl':'NOT_CHECKED','jcr_quartile':'NOT_DIRECTLY_VERIFIED','fit':'Preliminary: transfer-process mechanism/thermal model study; B03 is an older benchmark, not a recent journal-fit audit','final_journal':'NOT_SELECTED','full_policy_review':'PENDING: full recent-paper/article/data/code/AI/length review'},
 {'journal':'International Journal of Mechanical Sciences','print_issn':'0020-7403','eissn':'1879-2162','quartile_database':'SCImago/SJR (Scopus-based)','reporting_year':2025,'category':'Mechanical Engineering; Mechanics of Materials','quartile':'Q1 in listed categories','checked_date':DATE,'quartile_source':'https://www.scimagojr.com/journalsearch.php?q=50170&tip=sid','scie_evidence':'Publisher indexing list: SCIE + Scopus','index_source':'https://www.sciencedirect.com/journal/international-journal-of-mechanical-sciences/about/insights','independent_mjl':'NOT_CHECKED','jcr_quartile':'NOT_DIRECTLY_VERIFIED','fit':'Preliminary: engineering-relevant mechanical/material understanding; purely descriptive/generic mathematical work discouraged','final_journal':'NOT_SELECTED','full_policy_review':'PENDING: full recent-paper/article/data/code/AI/length review'}
]
gates = [
 {'gate':'Exact source model','status':'BLOCKED','evidence':'B01 full equations/case unavailable','before_execution':'Obtain/read source, restrictions, BCs/ICs; do not invent operators'},
 {'gate':'Explicit common limit','status':'NOT_DEFINED','evidence':'No selected new-model equations','before_execution':'Derive exact limiting map including initial-data compatibility'},
 {'gate':'Coupled reference reconstruction','status':'BLOCKED','evidence':'B02 preview only','before_execution':'Full source case and matched parameters/geometry/normalization'},
 {'gate':'Thermal-only reference reconstruction','status':'BLOCKED / alternative analytic controls possible','evidence':'B03 preview only','before_execution':'Full source or independently derived authorized control; label mathematical verification'},
 {'gate':'Material provenance','status':'PARTIAL','evidence':'B04 main conductivity source; B05/B06 correction; complete coupled/dynamic inputs not established','before_execution':'Consistent elastic/expansion/density/capacity/conductivity/dynamic inputs and uncertainty'},
 {'gate':'Physical validation of new T(t)/stress predictions','status':'NOT_STARTED; relevant evidence not established','evidence':'Property input evidence is not an independent prediction comparison','before_execution':'Matched measurement/evidence scope or explicitly approved restricted theoretical route'},
 {'gate':'Acceptance criteria','status':'NOT_DEFINED','evidence':'Final direction/Phase1 not approved','before_execution':'Quantity-specific errors and uncertainty; no universal5percent rule'},
 {'gate':'Research-direction approval','status':'NOT_APPROVED','evidence':'Only broad physics/symmetry scope confirmed','before_execution':'Explicit user shortlist/final problem decisions per workflow'},
 {'gate':'Pilot/execution','status':'NOT_AUTHORIZED / NOT_RUN','evidence':'Current permission is literature/benchmark screen','before_execution':'Approved phase, objective/scope/budget/diagnostics; preserve original outputs'},
 {'gate':'Production compute','status':'NOT_AUTHORIZED / NOT_RUN','evidence':'No method/DOF/runtime estimate or production plan','before_execution':'All science gates; explicit approval above ANY4CPU-h/1GPU-h/5GB'}
]
(REVIEW/'REFERENCE_SCREEN.json').write_text(json.dumps(refs,indent=2,ensure_ascii=False))
(REVIEW/'JOURNAL_SCREEN.json').write_text(json.dumps(journals,indent=2,ensure_ascii=False))

wb = Workbook(); wb.remove(wb.active)
navy='183449'; teal='DDEFF0'; amber='FFF1CC'; grey='F1F4F6'
def sheet(name, records):
 ws=wb.create_sheet(name); fields=list(records[0]);ws.append(fields)
 for r in records:ws.append([r.get(f,'') for f in fields])
 ws.freeze_panes='A2';ws.sheet_view.showGridLines=False
 for c in ws[1]:c.fill=PatternFill('solid',fgColor=navy);c.font=Font(name='Calibri',size=11,color='FFFFFF',bold=True);c.alignment=Alignment(wrap_text=True,vertical='center')
 ws.row_dimensions[1].height=36
 for row in ws.iter_rows(min_row=2):
  for c in row:
   c.font=Font(name='Calibri',size=10);c.alignment=Alignment(wrap_text=True,vertical='top');c.fill=PatternFill('solid',fgColor=grey if c.row%2==0 else 'FFFFFF')
   if c.value and ('BLOCKED' in str(c.value) or 'NOT_RUN' in str(c.value) or 'NOT_APPROVED' in str(c.value)):c.fill=PatternFill('solid',fgColor=amber)
   if isinstance(c.value,str) and c.value.startswith('https://'):c.hyperlink=c.value;c.font=Font(name='Calibri',size=10,color='17688C',underline='single')
  ws.row_dimensions[row[0].row].height=105
 for i,f in enumerate(fields,1):
  width=14 if f in ['id','year','reporting_year','quartile','checked_date'] else 34
  if f in ['title','claim_boundary','next_requirement','before_execution','fit','configuration','source_level']:width=48
  ws.column_dimensions[ws.cell(1,i).column_letter].width=width
 tab=Table(displayName=name.replace('_','')+'Table',ref=ws.dimensions);tab.tableStyleInfo=TableStyleInfo(name='TableStyleMedium2',showRowStripes=False);ws.add_table(tab)
 ws.auto_filter.ref=ws.dimensions
 return ws
readme=[
 {'item':'Task/date','statement':'Pre-execution published-journal/benchmark screen, 30 September2026, MASTER_PROMPTv2.1.'},
 {'item':'Overall status','statement':'PARTIAL. No formal Phase0A-2/2 completion, novelty confirmation, source-case reproduction or scientific execution.'},
 {'item':'Journal quartiles','statement':'SCImago/SJR2025 category rows; not automatically JCR. SCIE evidence is publisher-reported, not independently checked in Clarivate MJL.'},
 {'item':'Evidence level','statement':'Full material source B04 plus relevant2019 correction B06 inspected. Core model/reference B01–B03 only previews; no detailed equations inferred from snippets.'},
 {'item':'Origin integrity','statement':'Inputs300K sheet contains source-reported reference values, not computed project results, new measurements or approved parameters.'},
 {'item':'Verification vs validation','statement':'Limits/analytical comparisons verify mathematics/implementation. Material characterization and model-prediction validation are separate.'},
 {'item':'Execution','statement':'All project comparisons NOT_RUN. No guaranteed matching; no universal5percent acceptance threshold.'},
 {'item':'Research scope','statement':'User confirmed coupled thermoelasticity plus BOTH crystal and geometry symmetry. Exact material/model/geometry/journal still unapproved.'},
 {'item':'Next action','statement':'Obtain legitimate B01/B02 full texts, explicit source-reconstruction/shortlist authorization; stop before simulation.'}
]
sheet('Readme',readme);sheet('Published_refs',refs);sheet('Journal_status',journals);sheet('Evidence_gates',gates)
inputs=[
 {'component':'K11','source_value':12.13,'unit':'W/(m K)','basis':'B04 e2||b, e3||c; orthonormal frame','temperature':'300 K','origin':'SOURCE_REPORTED — conductivity derived from laser-flash diffusivity/density/database cp','source_id':'B04','use_status':'REFERENCE ONLY; NOT APPROVED PROJECT INPUT'},
 {'component':'K22','source_value':24.26,'unit':'W/(m K)','basis':'B04 e2||b, e3||c; orthonormal frame','temperature':'300 K','origin':'SOURCE_REPORTED — conductivity derived from laser-flash diffusivity/density/database cp','source_id':'B04','use_status':'REFERENCE ONLY; NOT APPROVED PROJECT INPUT'},
 {'component':'K33','source_value':14.09,'unit':'W/(m K)','basis':'B04 e2||b, e3||c; orthonormal frame','temperature':'300 K','origin':'SOURCE_REPORTED — reconstructed tensor component','source_id':'B04','use_status':'REFERENCE ONLY; NOT APPROVED PROJECT INPUT'},
 {'component':'K13=K31','source_value':-0.992,'unit':'W/(m K)','basis':'B04 e2||b, e3||c; orthonormal frame','temperature':'300 K','origin':'SOURCE_REPORTED — reconstructed tensor component','source_id':'B04','use_status':'REFERENCE ONLY; do not mix with B05 lab-frame component'},
]
sheet('Inputs300K',inputs);wb.save(REVIEW/'PRE_EXECUTION_SCREEN.xlsx')

controls={
 'DECISION_LOG.md':'''# Decision log\n\nDate:30 September2026.\n\n## D001 — Current master\nPrevious working rules:v2.0 and unapproved amendment suggestions. New decision:user supplied FINAL MASTER PROMPTv2.1; preserve it verbatim as canonical MASTER_PROMPT.md, sections0–90. Evidence:user message. Affected science/code/results:none. No scientific revalidation caused by saving the control text.\n\n## D002 — Scope and execution gate\nUser confirmed BOTH material/crystal and geometric symmetry and COUPLED THERMOELASTIC RESPONSE. User subsequently asked for published-journal/benchmark evidence review before execution. Current authorization is that bounded review, not automatic implementation/pilot/production. Final direction/model/material/journal remain unapproved.\n\n## D003 — Evidence classification\nLimiting-case and theoretical comparisons are verification, not automatically physical validation. Experimental property inputs do not independently validate a new model when copied into it. Agreeing with a source is not guaranteed or to be forced.\n\n## D004 — Source integrity\nCurrent review found2019 correction DOI10.1063/1.5088513 to Jiang2018 DOI10.1063/1.5054573. Future use must include corrected version and coordinate mapping. The beta-Ga2O3/new-model proposal remains provisional. Affected current equations/code/results:none because no new model was implemented/run. Recheck/revalidate any future input derived from that source.\n\n## D005 — Source-access blocker\nCore recent-model/coupled benchmark full equations are not obtained. Do not invent them from abstracts or silently substitute an older model. Request legitimate PDFs and exact next-task approval. Journal-family checks are provisional, not final submission selection.\n''',
 'CHANGELOG.md':'''# Changelog\n\n## 2026-09-30 — Control/evidence update\n- Stored user-supplied MASTER_PROMPTv2.1 plus version/date/checksum; prior v2.0 working-control text is superseded, historical reports retained.\n- Added a bounded pre-execution journal/reference/evidence screen, workbook and logs.\n- Read full5-page Klimm material-characterization source and2019 APL correction text; no numerical model was executed.\n- Recorded2025 primary SCImago category quartiles and current publisher indexing lists separately from unverified current JCR quartiles.\n- Held uncorrected tensor import and broader physical-prediction claims pending source/mapping/data.\n- Created a notes/control recovery checkpoint, excluding original/third-party source inputs.\n- No original bibliography, manuscript, code, model equation, parameter set or numerical result was altered.\n''',
 'VALIDATION_STATUS.md':'''# Verification and physical-validation status\n\nDate:30 September2026. See MASTER_PROMPTv2.1 and PROJECT_STATE_PRE_EXECUTION_REVIEW_01.md.\n\n## New research project\nFinal direction/model/evidence route:NOT_APPROVED.\nVerification:NOT_STARTED. B01–B03 potential routes identified; none reconstructed or compared.\nPhysical validation:NOT_STARTED. Property-characterization evidence is available in B04/B05, but no independent model/experiment comparison was run. For proposed non-Fourier beta-Ga2O3 transient temperature/stress predictions, suitable matched evidence was not established in this bounded review:APPLICABLE — EVIDENCE_UNAVAILABLE (provisional, not proof of absence). NOT_APPLICABLE has not been justified.\n\n## Relevant source status\nB01 recent model:BLOCKED by full equations/case access.\nB02 coupled limiting reference:BLOCKED by full case reconstruction.\nB03 thermal-only reference:BLOCKED by full case reconstruction; cannot validate stress.\nB04 main experimental property source:FULL_TEXT/RELEVANT_EQUATIONS_INSPECTED; supporting tables/detector curves not obtained; reference values not project outputs.\nB05/B06:published correction exists/main correction read; numerical corrected-input import not done.\n\nNo PASS, quantitative agreement, convergence or validated scope for the new model is reported. Source retrieval failures are not failed validation tests. The user's older manuscript claims and archived FEM4 PASS reports remain independently unreproduced here.\n''',
 'COMPUTE_STATUS.md':'''# Compute status\n\nDate:30 September2026.\n\nScientific model implementation:NOT_STARTED.\nScientific solver/pilot/production runs in current work:0.\nBenchmark/convergence/physical-validation comparisons:NOT_RUN.\n\nExecuted non-scientific processing:public metadata/PDF retrieval, PDF text extraction/rendering, checksums, source inventories and document/workbook/checkpoint creation. These are not research simulations or proof of solver correctness.\n\nUser hardware, software licences/runtime, compute capability, timeline and experiment access:UNKNOWN. Workspace Python/package metadata is recorded in PRE_EXECUTION_REVIEW/ARTIFACT_BUILD_ENVIRONMENT.json; it is not the user's machine. MATLAB/Octave were not available in the prior code-reading environment; availability snapshot in this build is recorded separately.\n\nProduction estimates for selected equations/DOFs/method:NOT_DEFINED; no observed solver runtime or memory is claimed.\n\nDefault user-policy approval thresholds:any estimated production total above4CPU-hours OR1GPU-hour OR5GB generated data requires explicit approval unless RESEARCH_PROFILE.md is explicitly updated by the user. A pilot requires an explicitly authorized phase/objective/scope/budget/diagnostics regardless of those production thresholds. No approval exists.\n''',
 'REPRODUCIBILITY_STATUS.md':'''# Reproducibility status\n\nDate:30 September2026.\n\nNew scientific source code/environment:NOT_STARTED.\nReference-case reconstruction:NOT_RUN.\nValidation reproduction:NOT_RUN.\nConvergence/error-study reproduction:NOT_RUN.\nPrincipal result/figure/table reproduction:NOT_RUN.\n\nInput reading and source-screening provenance:available in recorded manifests/logs. Metadata/workbook artifact construction:RUN_SUCCESS when BUILD_REVIEW_ARTIFACTS.py completes, not scientific numerical reproduction.\n\nRECOVERY_PRE_EXECUTION_REVIEW_01.zip is a notes/control checkpoint. It includes canonical master, current control/state, screening tables/logs and prior summaries/manifests. It deliberately excludes third-party PDFs/images/full extracted paper texts and original manuscript/code archives. Inputs remain accessible in the shared workspace through recorded paths/URLs/checksums; the ZIP is NOT an offline-complete source/input or final-research package. Third-party redistribution rights must be checked before a future final archive.\n''',
 'RESEARCH_PROFILE.md':'''# Research profile — observed and pending\n\nDate:30 September2026. Status:input-grounded working record, not an approved complete project profile.\n\nUser-confirmed current aim:recent heat-conduction model; coupled thermoelastic response; BOTH material/crystal symmetry and geometric symmetry. Q1/SCI is target positioning under MASTER_PROMPTv2.1, not a guarantee.\n\nObserved inputs:published bibliography, eight supplied unpublished PDFs, eight representative accessible published full texts, and FEM4 MATLAB source/result/manuscript package. Their provenance/inventories are preserved. Paper ownership/publication status and manuscript claims are not universally independently certified.\n\nObserved infrastructure:static2D C1 BFS electromechanical/strain-gradient MATLAB program, not an existing transient thermal solver. Three Python figure helpers are also supplied. Method/language preference is not confirmed; do not force BFS/FEM/MATLAB.\n\nProvisional direction only:2025 generalized CV/GN family with monoclinic beta-Ga2O3 and circular/elliptical cavity symmetry mismatch. Novelty/model/direction/journal approval:NOT_GRANTED.\n\nUnknown:user hardware/compute, installed scientific runtimes/licences, experimental access, deadline, costs/APC preferences, intended exact Google Drive source, final material/model branch and research-type evidence route. Do not fill these from assumptions or repository names.\n\nDefault production approval thresholds:4CPU-hours,1GPU-hour,5GB generated data (ANY exceeded requires explicit approval). No user override or production approval.\n''',
 'REJECTED_IDEAS.md':'''# Rejected shortcuts / held options\n\nDate:30 September2026. No user-approved research direction was rejected or replaced.\n\nRejected shortcuts:\n- Calling a limiting/numerical/theoretical comparison physical validation by default.\n- Copying experimental conductivity into a model and treating that same-data equality as independent physical validation.\n- Using an uncorrected2018 tensor or mixing crystal-coordinate frames.\n- Treating an axisymmetric isotropic/radially orthotropic reference as a fixed-Cartesian monoclinic solution.\n- Treating a different source BC/finite-vs-infinite geometry as a matched case without an explicit map.\n- Claiming Q1/JCR/SCIE as a single unqualified property or using journal prestige as proof of scientific correctness.\n- Inventing inaccessible recent-model operators/parameters/results or guaranteeing a benchmark match.\n\nHeld, not globally rejected:beta-Ga2O3/model/cavity suggestion pending reconstructable equations/data, novelty, significance and user approval. All concerns are revisitable with evidence.\n''',
 'CURRENT_PROJECT_STATE.md':'''# Current project state pointer\n\nRead MASTER_PROMPT.md (v2.1), then PROJECT_STATE_PRE_EXECUTION_REVIEW_01.md and the root decision/status files. No numbered research phase has been fully approved/completed; current bounded source review is PARTIAL. Do not start simulations automatically.\n'''
}
for name,text in controls.items():
 p=ROOT/name
 if p.exists():raise RuntimeError(f'Refusing silent overwrite of control file {p}')
 p.write_text(text)

env={'date':DATE,'purpose':'Document/artifact building and source processing; NOT scientific simulation','python':platform.python_version(),'platform':platform.platform(),'matlab_path':shutil.which('matlab'),'octave_path':shutil.which('octave')}
for pkg in ['openpyxl','requests','PyMuPDF','scipy','sympy']:
 try:env[pkg]=version(pkg)
 except PackageNotFoundError:env[pkg]='NOT_FOUND'
(REVIEW/'ARTIFACT_BUILD_ENVIRONMENT.json').write_text(json.dumps(env,indent=2))

# Recovery checkpoint: metadata and agent-written notes only; no third-party full texts/images/inputs.
include=[ROOT/n for n in ['MASTER_PROMPT.md','MASTER_PROMPT_VERSION','MASTER_PROMPT_DATE','PROJECT_STATE_PRE_EXECUTION_REVIEW_01.md']+list(controls)]
include+=list((ROOT/'PROJECT_CONTROL').glob('*.json'))
include += [REVIEW/n for n in ['JOURNAL_BENCHMARK_SCREENING.md','SEARCH_LOG.md','EVIDENCE_LOG.md','PRE_EXECUTION_SCREEN.xlsx','REFERENCE_SCREEN.json','JOURNAL_SCREEN.json','OPEN_ACCESS_LOCATION_CHECKS.json','ARTIFACT_BUILD_ENVIRONMENT.json','BUILD_REVIEW_ARTIFACTS.py']]
include += list((REVIEW/'SOURCES').glob('*.json'))
for folder in ['RESEARCH_READING','HEAT_MODEL_EXPLORATION','CODE_REVIEW/FEM4_PACKAGE']:
 base=ROOT/folder
 for p in base.rglob('*'):
  if not p.is_file() or p.suffix not in ['.md','.csv','.json']:continue
  # Exclude entire extracted/excerpted third-party text corpora even where in JSON.
  if any(s in str(p.relative_to(base)) for s in ['EXTRACTED_','READING_EXTRACTS']):continue
  include.append(p)
include=sorted(set(include));missing=[str(p) for p in include if not p.exists()]
assert not missing,missing
manifest=[{'path':str(p.relative_to(ROOT)),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in include]
(REVIEW/'RECOVERY_MANIFEST.json').write_text(json.dumps({'date':DATE,'kind':'Notes/control checkpoint — NOT offline-complete input/source or final research archive','excluded':'Original inputs/code/manuscript archives, third-party PDFs/images and full extracted text','files':manifest},indent=2))
archive=REVIEW/'RECOVERY_PRE_EXECUTION_REVIEW_01.zip'
with zipfile.ZipFile(archive,'w',zipfile.ZIP_DEFLATED) as z:
 for p in include:z.write(p,str(p.relative_to(ROOT)))
 z.write(REVIEW/'RECOVERY_MANIFEST.json','PRE_EXECUTION_REVIEW/RECOVERY_MANIFEST.json')
assert zipfile.ZipFile(archive).testzip() is None
check=load_workbook(REVIEW/'PRE_EXECUTION_SCREEN.xlsx',read_only=True)
assert check['Published_refs'].max_row==7
assert check['Journal_status'].max_row==4
assert all(r['project_comparison']=='NOT_RUN' for r in refs)
print('WORKBOOK_CREATED',check.sheetnames)
print('CHECKPOINT_CREATED',archive.name,archive.stat().st_size,'bytes',len(include)+1,'files')
print('ARTIFACT_BUILD_RUN_SUCCESS — document handling only; scientific solver/validation/production NOT_RUN')
