#!/usr/bin/env python3
"""Phase 10 - build the downloadable submission bundle.

One zip containing exactly what the journal submission needs, plus the checks the
reader will want:

    IJHMT_submission_bundle.zip
      MANUSCRIPT/FINAL_REVISED_MANUSCRIPT.tex        the LaTeX source (elsarticle-num)
      MANUSCRIPT/FINAL_REVISED_CALCULATIONS.tex      the companion source
      MANUSCRIPT/FINAL_REVISED_REFERENCES.bib        the 55-entry bibliography
      MANUSCRIPT/figures/fig*.pdf                    the eight vector figures
      MANUSCRIPT/manuscript_IJHMT.md                 the Markdown sources of truth
      MANUSCRIPT/calculations_IJHMT.md
      MANUSCRIPT/manuscript_IJHMT.pdf                the locally rendered previews
      MANUSCRIPT/calculations_IJHMT.pdf
      MANUSCRIPT/highlights.txt                      highlights as a plain-text file
      SUPPLEMENTARY/SUPPLEMENTARY_TABLES.xlsx        the supplementary material
      COVER_LETTER/cover_letter.md|docx|pdf           the letter in text + upload formats
      CHECKLIST/SUBMISSION_CHECKLIST.md              what is machine-checked vs author-blocked
      CHECKLIST/AUTHOR_INPUT_REQUIRED.md             the author-input list
      PROVENANCE/CODE_FREEZE_submission_2026_10_03j.json   the deposit manifest
      PROVENANCE/README.txt                          how each file was produced and verified
      MANIFEST.json                                  sha256 + byte size for every file above

The full deposit package (raw per-run outputs, convergence families, the whole code
tree) is NOT here: it is ~45 MB of research data and is regenerated by
`python3 PAPER_PROJECT/00_Project_Control/make_packages.py final` into
`PAPER_PROJECT/packages/`, which the repository gitignores on purpose.

Deterministic: file order sorted, fixed zip timestamp, so rebuilding gives the same bytes.
"""
import hashlib
import json
import os
import zipfile
from datetime import datetime, timezone

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
OUT = os.path.join(ROOT, 'Phase_10_Submission_Package', 'IJHMT_submission_bundle.zip')
MS = os.path.join(ROOT, 'PAPER_PROJECT', '13_Manuscript')
NOW = datetime(2026, 10, 3, 0, 0, 0, tzinfo=timezone.utc)

FILES = [
    ('MANUSCRIPT/FINAL_REVISED_MANUSCRIPT.tex', os.path.join(MS, 'FINAL_REVISED_MANUSCRIPT.tex')),
    ('MANUSCRIPT/FINAL_REVISED_CALCULATIONS.tex', os.path.join(MS, 'FINAL_REVISED_CALCULATIONS.tex')),
    ('MANUSCRIPT/FINAL_REVISED_REFERENCES.bib', os.path.join(MS, 'FINAL_REVISED_REFERENCES.bib')),
    ('MANUSCRIPT/manuscript_IJHMT.md', os.path.join(MS, 'manuscript_IJHMT.md')),
    ('MANUSCRIPT/calculations_IJHMT.md', os.path.join(MS, 'calculations_IJHMT.md')),
    ('MANUSCRIPT/manuscript_IJHMT.pdf', os.path.join(MS, 'manuscript_IJHMT.pdf')),
    ('MANUSCRIPT/calculations_IJHMT.pdf', os.path.join(MS, 'calculations_IJHMT.pdf')),
    ('MANUSCRIPT/highlights.txt', os.path.join(MS, 'highlights.txt')),
    ('SUPPLEMENTARY/SUPPLEMENTARY_TABLES.xlsx', os.path.join(MS, 'SUPPLEMENTARY_TABLES.xlsx')),
    ('COVER_LETTER/cover_letter.md', os.path.join(MS, 'cover_letter.md')),
    ('COVER_LETTER/cover_letter.docx', os.path.join(ROOT, 'Phase_10_Submission_Package', 'cover_letter.docx')),
    ('COVER_LETTER/cover_letter.pdf', os.path.join(ROOT, 'Phase_10_Submission_Package', 'cover_letter.pdf')),
    ('CHECKLIST/SUBMISSION_CHECKLIST.md', os.path.join(ROOT, 'Phase_08_Final_Audit', 'SUBMISSION_CHECKLIST.md')),
    ('CHECKLIST/AUTHOR_INPUT_REQUIRED.md', os.path.join(MS, 'AUTHOR_INPUT_REQUIRED.md')),
    ('PROVENANCE/CODE_FREEZE_submission_2026_10_03j.json',
     os.path.join(ROOT, 'PAPER_PROJECT', '06_Source_Code', 'CODE_FREEZE_submission_2026_10_03j.json')),
]

README = """How this bundle was produced, and what is in it
=============================================

Target: International Journal of Heat and Mass Transfer (Elsevier, `elsarticle`,
numbered style). Every file here is generated from the project's own builders;
nothing in the bundle is hand-edited, so re-running the build reproduces it.

Sources of truth
  MANUSCRIPT/*.md          built by PAPER_PROJECT/13_Manuscript/build_manuscript.py and
                           build_calculations.py from the data package (no number is typed
                           into the text; each is read from the analysis outputs or the
                           frozen code).
  MANUSCRIPT/*.tex         built by tools/md_to_tex.py from those .md files. The .tex files
                           use \\graphicspath{{figures/}} and reference the figures by name,
                           so the MANUSCRIPT folder plus MANUSCRIPT/figures/ compiles on its
                           own: pdflatex, bibtex, pdflatex, pdflatex.
  MANUSCRIPT/figures/*.pdf the eight vector renditions exported from the frozen figure
                           script (08_Experiments/make_figures.py) at 600 dpi / PDF by
                           Phase_09_Closeout and Phase_10_Submission_Package.
  MANUSCRIPT/*.pdf         previews rendered from the .md (they embed the 200-dpi PNGs the
                           project has always used, so their provenance is unchanged).
  MANUSCRIPT/highlights.txt identical to the Highlights block in the manuscript.

Supplementary material
  SUPPLEMENTARY/SUPPLEMENTARY_TABLES.xlsx  8 sheets (README, Verification,
                           PhiSweep_ellipse, Convergence_6phi, D_lambda_eps, Ablations,
                           Parameters, Production_runs), built by build_supplement.py from
                           the same analysis outputs; it satisfies the "(full table:
                           supplementary material)" promise in the Table 2 caption.

Author-owned fields still bracketed
  COVER_LETTER/*, and the same placeholders inside the .tex/.md: author names,
  affiliations, ORCID iDs, corresponding author, funding, competing interest, CRediT
  statement, and the public repository DOI for the data package. See
  CHECKLIST/AUTHOR_INPUT_REQUIRED.md. Nothing here invents those values.

Verification record
  CHECKLIST/SUBMISSION_CHECKLIST.md lists what passed the machine checks:
  tools/audit_tex.py, tools/check_crossrefs.py, tools/check_tex_commands.py,
  tools/test_md_to_tex.py, tools/verify_pdf.py (manuscript and companion), and
  Phase_08_Final_Audit/verification/final_consistency.py (0 failures: 55 references
  identical across .md/.bib/.tex/PDF, numbered in ascending order of first appearance,
  no orphan and no dangling key, structure and limits conforming).
  PROVENANCE/CODE_FREEZE_submission_2026_10_03j.json is the SHA-256 manifest of the 27
  frozen source files behind every number; its entries were re-hashed against the code.
  The .tex files have not been compiled in the environment that produced them (no TeX
  engine there); run Phase_10_Submission_Package/compile_check.sh on a machine with TeX
  Live before uploading and keep COMPILE_CHECK.txt.

Not included (by design)
  The raw research data (per-run .npz/.json outputs, convergence families, figure
  scripts, the whole code tree) belongs to the deposit package, not the manuscript
  upload. Rebuild it with:
      python3 PAPER_PROJECT/00_Project_Control/make_packages.py final
  giving PAPER_PROJECT/packages/RESEARCH_PROJECT_FINAL.zip (~45 MB, MANIFEST.json with a
  SHA-256 per file). That zip is the object to deposit in a public repository to obtain
  the DOI quoted in the Data availability statement.
"""


def sha256(path):
    h = hashlib.sha256()
    with open(path, 'rb') as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b''):
            h.update(chunk)
    return h.hexdigest()


def main():
    # make sure the figure folder that the .tex needs is present in the tree
    figs = sorted(os.listdir(os.path.join(MS, 'figures'))) if os.path.isdir(os.path.join(MS, 'figures')) else []
    figs = [f for f in figs if f.endswith('.pdf')]
    if len(figs) != 8:
        raise SystemExit('MANUSCRIPT/figures must hold the 8 vector PDFs; found %d - run '
                         'Phase_10_Submission_Package/verification/make_tex_figure_set.py' % len(figs))
    manifest = []
    entries = list(FILES) + [('MANUSCRIPT/figures/' + f, os.path.join(MS, 'figures', f)) for f in figs]
    if os.path.isfile(os.path.join(MS, 'figures', 'README.txt')):
        entries.append(('MANUSCRIPT/figures/README.txt', os.path.join(MS, 'figures', 'README.txt')))
    if os.path.isfile(os.path.join(MS, 'PDF_VERIFICATION.txt')):
        entries.append(('PROVENANCE/PDF_VERIFICATION.txt', os.path.join(MS, 'PDF_VERIFICATION.txt')))
    if os.path.isfile(os.path.join(MS, 'REF_ORDER.json')):
        entries.append(('PROVENANCE/REF_ORDER.json', os.path.join(MS, 'REF_ORDER.json')))
    if os.path.isfile(os.path.join(MS, 'REFERENCES_ORDERED.json')):
        entries.append(('PROVENANCE/REFERENCES_ORDERED.json', os.path.join(MS, 'REFERENCES_ORDERED.json')))

    if os.path.exists(OUT):
        os.remove(OUT)
    missing = []
    with zipfile.ZipFile(OUT, 'w', zipfile.ZIP_DEFLATED, compresslevel=9) as z:
        for arc, src in sorted(entries, key=lambda e: e[0]):
            if not os.path.isfile(src):
                missing.append(arc)
                continue
            z.write(src, arc)
            manifest.append({'path': arc, 'bytes': os.path.getsize(src), 'sha256': sha256(src)})
        zi = zipfile.ZipInfo('PROVENANCE/README.txt', date_time=(NOW.year, NOW.month, NOW.day, 0, 0, 0))
        zi.compress_type = zipfile.ZIP_DEFLATED
        z.writestr(zi, README)
        zi = zipfile.ZipInfo('MANIFEST.json', date_time=(NOW.year, NOW.month, NOW.day, 0, 0, 0))
        zi.compress_type = zipfile.ZIP_DEFLATED
        z.writestr(zi, json.dumps({'generated': NOW.isoformat(), 'files': manifest}, indent=1) + '\n')
    if missing:
        print('WARNING missing from the bundle: %s' % missing)
    print('wrote %s (%d B, %d files + MANIFEST.json + README.txt)'
          % (os.path.relpath(OUT, ROOT), os.path.getsize(OUT), len(manifest)))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
