#!/usr/bin/env python3
"""audit_phase4.py — Phase 4: figures and tables, regenerated from verified data and re-proved.

Three checks, all read-only apart from rebuilding the generated documents (which must come out identical):

  T1 determinism.  Every table in both documents is generated by a builder from a stored artefact, so
     rebuilding the documents from the unchanged code must reproduce the current Markdown byte for byte.
  T2 cell provenance.  Every number in a Markdown table cell is looked up in the artefact the builder reads
     (TEST_RESULTS.json, ANALYSIS_V2.json, CONVERGENCE*.json, MANUSCRIPT_STATS.json) after applying the same
     formatting the builder uses; a cell whose value is in no source is a defect.
  T3 carried literals.  Numbers in prose and in figure captions are listed with whether the same value occurs
     in any stored source; unmatched ones are the hand-carried figures the audit must be able to explain.

Writes verification/phase4_tables.json.  Exits 1 if T1 or T2 fails.
"""
import json
import os
import re
import shutil
import subprocess
import sys

R = '/home/user/le'
M = f'{R}/PAPER_PROJECT/13_Manuscript'
V = '/home/user/.venv-q1/bin/python'
OUT = {}


def run(cmd, cwd):
    p = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    return p.returncode, (p.stdout + p.stderr).strip()


# ---------------------------------------------------------------- T1 determinism
before = {}
for f in ('manuscript_IJHMT.md', 'calculations_IJHMT.md', 'SUPPLEMENTARY_TABLES.xlsx', 'highlights.txt'):
    before[f] = open(f'{M}/{f}', 'rb').read()
rcs = {}
for script in ('build_manuscript.py', 'build_calculations.py', 'build_supplement.py'):
    rcs[script] = run([V, f'{M}/{script}'], R)
def _xlsx_cells(path):
    from openpyxl import load_workbook
    wb = load_workbook(path)
    return {ws.title: [[c.value for c in row] for row in ws.iter_rows()] for ws in wb.worksheets}


changed, xlsx_equal = [], None
for f, b in before.items():
    a = open(f'{M}/{f}', 'rb').read()
    if a == b:
        continue
    if f.endswith('.xlsx'):
        # a workbook is not byte-reproducible: openpyxl writes a creation timestamp into docProps.
        # The reproducibility claim is about the content, so compare the cell values of every sheet.
        tmp = '/tmp/_prev_suppl.xlsx'
        open(tmp, 'wb').write(b)
        xlsx_equal = _xlsx_cells(tmp) == _xlsx_cells(f'{M}/{f}')
        if xlsx_equal:
            continue
    changed.append(f)
OUT['T1'] = {'status': 'PASS' if not changed and all(rc == 0 for rc, _ in rcs.values()) else 'FAIL',
             'builders': {k: (v[0], v[1].splitlines()[-1] if v[1] else '') for k, v in rcs.items()},
             'changed_files': changed,
             'supplementary_workbook_cells_equal': xlsx_equal,
             'claim': 'rebuilding from the unchanged code reproduces both Markdown documents and the highlights '
                      'byte for byte, and the supplementary workbook sheet by sheet (its bytes differ only by the '
                      'creation timestamp openpyxl writes); so no table or caption was hand-edited into a '
                      'generated file'}
print('T1', OUT['T1']['status'], 'changed:', changed or 'none')

# ---------------------------------------------------------------- sources
PROJ = f'{R}/PAPER_PROJECT'
src = {}
for path in ('07_Tests/TEST_RESULTS.json', '10_Processed_Data/ANALYSIS_V2.json',
             '10_Processed_Data/CONVERGENCE_RESULTS.json', '10_Processed_Data/CONVERGENCE_DIRS.json',
             '13_Manuscript/MANUSCRIPT_STATS.json'):
    p = os.path.join(PROJ, path)
    if os.path.exists(p):
        src[path] = json.load(open(p))


def walk(o, acc):
    if isinstance(o, dict):
        for v in o.values():
            walk(v, acc)
    elif isinstance(o, list):
        for v in o:
            walk(v, acc)
    elif isinstance(o, bool):
        pass
    elif isinstance(o, (int, float)):
        acc.add(float(o))
        for d in range(1, 7):
            try:
                acc.add(float('%.*e' % (d - 1, o)))
                acc.add(round(float(('%.' + str(d) + 'f') % o), d))
            except (ValueError, OverflowError):
                pass
        acc.add(float('%.3g' % o))
    elif isinstance(o, str):
        for m in re.finditer(r'-?\d+\.?\d*(?:[eE][-+]?\d+)?', o):
            try:
                acc.add(float(m.group()))
            except ValueError:
                pass
    return acc


values = set()
for k, v in src.items():
    walk(v, values)
for extra in ('10_Processed_Data/ANALYSIS_V2_TABLES.md', '06_Source_Code/PARAMETER_TABLE.md',
              '10_Processed_Data/PRODUCTION_PROVENANCE.csv'):
    _p = os.path.join(PROJ, extra)
    if os.path.exists(_p):
        walk(open(_p).read(), values)
# the closed-form constants the builders compute rather than read
sys.path.insert(0, f'{PROJ}/13_Manuscript'); sys.path.insert(0, f'{PROJ}/06_Source_Code/src')
try:
    import numpy as np
    import cg_model as CM
    import ms_static as MS
    import cg_grid as CG
    walk([CG.Grid(a=1.0).Nr, CG.Grid(a=1.0).Nt, CG.Grid(a=1.0).R, CG.Grid(a=1.0).gamma], values)
    der = CM.derived()
    for v in der.values():
        walk(v, values)
    for nm in ('DELTA_T', 'DELTA_MIN', 'DELTA_MAX', 'SPREAD_REL', 'TRAIN_MEAN_OVER_PEAK', 'PSQ', 'PSB'):
        if hasattr(MS, nm):
            walk(float(getattr(MS, nm)), values)
    for _k, _v in getattr(CM, 'Cij_GPa', {}).items():
        walk(float(_v), values)
    walk(getattr(CM, 'alpha_crys', []), values)
    walk(getattr(CM, 'K_ac', []), values)
    for _k in ('rho', 'cp_ESTIMATED', 'T0'):
        walk(float(getattr(CM, _k)), values)
    OUT['T1']['builder_constants_imported'] = True
except Exception as e:                                            # pragma: no cover
    OUT['T1']['builder_constants_imported'] = str(e)


def present(x, tol=0.0):
    for v in values:
        if v == 0 and x == 0:
            return True
        if v != 0 and abs(x - v) <= max(tol, 1e-3 * abs(v)):
            return True
    return False


CELL = re.compile(r'(?:^|\|)\s*:?-{2,}')


def tables(md):
    """yield (table_index, row_index, [cells]) for every pipe table in the document."""
    lines = md.split('\n')
    i, ti = 0, 0
    while i < len(lines):
        if lines[i].startswith('|') and i + 1 < len(lines) and CELL.search(lines[i + 1]):
            ti += 1
            rows = []
            j = i
            while j < len(lines) and lines[j].startswith('|'):
                rows.append([c.strip() for c in lines[j].strip().strip('|').split('|')])
                j += 1
            for ri, r in enumerate(rows):
                if ri >= 2:
                    yield ti, ri, r
            i = j
        else:
            i += 1


NUM = re.compile(r'-?\d+\.\d+(?:[eE][-+]?\d+)?|-?\d+\.\d*')
t2 = {'status': 'PASS', 'tables_checked': 0, 'cells_with_numbers': 0, 'unmatched': []}
for doc in ('manuscript_IJHMT.md', 'calculations_IJHMT.md'):
    md = open(f'{M}/{doc}').read()
    seen = set()
    for ti, ri, cells in tables(md):
        t2['tables_checked'] += 0
        seen.add((doc, ti))
        for c in cells:
            for mm in NUM.finditer(c):
                try:
                    x = float(mm.group())
                except ValueError:
                    continue
                if abs(x) < 1e-12 or abs(x) in (0.0, 1.0, 2.0):
                    continue
                t2['cells_with_numbers'] += 1
                if not present(x):
                    t2['unmatched'].append({'doc': doc, 'table': ti, 'row': ri, 'value': mm.group()})
    t2['tables_checked'] += len(seen)
if t2['unmatched']:
    t2['status'] = 'REVIEW'
OUT['T2'] = t2
print('T2', t2['status'], "%d numeric cells in %d tables, %d unmatched"
      % (t2['cells_with_numbers'], t2['tables_checked'], len(t2['unmatched'])))
for u in t2['unmatched'][:10]:
    print('    unmatched:', u)

# ---------------------------------------------------------------- T3 carried literals
CAP = re.compile(r'^\s*(\*\*)?(Fig|Figure|Table)', re.I)
t3 = {'prose_numbers': 0, 'unmatched': []}
for doc in ('manuscript_IJHMT.md', 'calculations_IJHMT.md'):
    md = open(f'{M}/{doc}').read().split('\n')
    in_table = False
    for n, line in enumerate(md, 1):
        if line.startswith('|'):
            continue
        if line.startswith('#') or line.strip() == '':
            continue
        for mm in NUM.finditer(line):
            try:
                x = float(mm.group())
            except ValueError:
                continue
            if abs(x) < 1e-9:
                continue
            t3['prose_numbers'] += 1
            if not present(x, tol=5e-3 * max(1e-30, abs(x))):
                t3['unmatched'].append({'doc': doc, 'line': n, 'value': mm.group(),
                                        'caption': bool(CAP.match(line)),
                                        'text': line.strip()[:110]})
uniq = {}
for u in t3['unmatched']:
    uniq.setdefault(u['value'], u)
t3['unmatched_distinct'] = len(uniq)
t3['unmatched_total'] = len(t3['unmatched'])
t3['status'] = 'REVIEW' if uniq else 'PASS'
t3['examples'] = list(uniq.values())[:40]
del t3['unmatched']
OUT['T3'] = t3
print('T3', t3['status'], '%d prose/caption numbers, %d not found in a stored source (%d distinct)'
      % (t3['prose_numbers'], t3['unmatched_total'], t3['unmatched_distinct']))

# ---------------------------------------------------------------- figures (record of the regeneration)
fd = f'{M}/../../Phase_04_Figures_Tables/verification/figure_render_diff.json'
OUT['T1']['figures'] = json.load(open(f'{R}/Phase_04_Figures_Tables/verification/figure_render_diff.json'))
OUT['summary'] = {'T1': OUT['T1']['status'], 'T2': t2['status'], 'T3': t3['status']}
open(f'{R}/Phase_04_Figures_Tables/verification/phase4_tables.json', 'w').write(json.dumps(OUT, indent=2))
print('\n', OUT['summary'])
sys.exit(1 if any(v == 'FAIL' for v in OUT['summary'].values()) else 0)
