#!/usr/bin/env python3
"""refs_to_bib.py — build FINAL_REVISED_REFERENCES.bib from the project's verified reference list.

Source: PAPER_PROJECT/01_Literature/REFERENCES_VERIFIED.json (54 entries; each carries a
"METADATA VERIFIED (Crossref ...)" level).  Nothing is invented: the BibTeX fields are
parsed out of the stored, verified one-line reference strings, and the file is written with the
same numbering the manuscript uses.  Books and book chapters are emitted as @book and
@incollection instead of falling through to the @misc fallback.

Usage:
    python3 tools/refs_to_bib.py [-o PAPER_PROJECT/13_Manuscript/FINAL_REVISED_REFERENCES.bib]
"""
import argparse
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DEFAULT_SRC = os.path.join(ROOT, 'PAPER_PROJECT', '01_Literature', 'REFERENCES_VERIFIED.json')
DEFAULT_OUT = os.path.join(ROOT, 'PAPER_PROJECT', '13_Manuscript', 'FINAL_REVISED_REFERENCES.bib')

DOI_RE = re.compile(r'https?://(?:dx\.)?doi\.org/(\S+?)\.?\s*$')
CITE_RE = re.compile(
    r'^(?P<authors>.+?)\.\s+'
    r'(?P<title>.+?)\.\s+'
    r'(?P<journal>.+?),\s*'
    r'(?P<volume>\d+)\s*'
    r'(?:\((?P<number>[^)]+)\))?\s*,\s*'
    r'(?P<pages>[^(]+?)\s*'
    r'\((?P<year>(?:19|20)\d\d)\)\.?\s*$')
INITIALS_RE = re.compile(r'^[A-Z]\.([A-Z]\.)*[A-Z]?$')

# Books:    "Authors. Title. Publisher, Series (year). doi"
BOOK_RE = re.compile(
    r'^(?P<authors>.+?)\.\s+'
    r'(?P<title>.+?)\.\s+'
    r'(?P<publisher>[^(]+?)\s*'
    r'\((?P<year>(?:19|20)\d\d)\)\.?\s*$')
# Chapters: "Authors. Title. In Book, pages (year). doi"
CHAP_RE = re.compile(
    r'^(?P<authors>.+?)\.\s+'
    r'(?P<title>.+?)\.\s+'
    r'In\s+(?P<booktitle>.+?),\s*'
    r'(?P<pages>[^(]+?)\s*'
    r'\((?P<year>(?:19|20)\d\d)\)\.?\s*$')


def texify(s):
    """escape what LaTeX needs escaped and put chemistry/Greek into math mode"""
    s = s.replace('&', '\\&').replace('%', '\\%').replace('#', '\\#')
    s = re.sub(r'Ga(\d)O(\d)', r'Ga$_\1$O$_\2$', s)          # Ga2O3 -> Ga$_2$O$_3$
    for g, m in (('\u03b2', '\\beta'), ('\u03b1', '\\alpha'), ('\u03ba', '\\kappa')):
        s = s.replace(g + '-', '$%s$-' % m).replace(g, '$%s$' % m)
    return s


def bib_authors(a):
    """'Florence, A.L., Goodier, J.N., et al.' -> 'Florence, A. L. and Goodier, J. N. and others'"""
    a = a.strip()
    if re.search(r'(?:^|[\s,])[A-Z]$', a):
        a += '.'          # the citation regex ate the period of the last initial
    toks = [t.strip() for t in a.split(',')]
    out, cur = [], toks[0]
    for t in toks[1:]:
        if INITIALS_RE.match(t):                       # initials belonging to the current name
            cur = cur + ', ' + t
        else:
            out.append(cur)
            cur = t
    out.append(cur)
    names = []
    for n in out:
        if n.lower().startswith('et al'):
            names.append('others')
            continue
        last, _, initials = n.partition(',')
        initials = ' '.join(x for x in initials.split() if x)
        initials = re.sub(r'([A-Z])\.', r'\1. ', initials).strip()
        names.append(f'{last.strip()}, {initials}'.strip().rstrip(','))
    return ' and '.join(names)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('-i', '--input', default=DEFAULT_SRC)
    ap.add_argument('-o', '--output', default=DEFAULT_OUT)
    a = ap.parse_args()

    refs = json.load(open(a.input, encoding='utf-8'))
    lines = ['% FINAL_REVISED_REFERENCES.bib',
             '% Generated by tools/refs_to_bib.py from 01_Literature/REFERENCES_VERIFIED.json.',
             '% Every entry comes from that verified list; no metadata was added or invented.',
             '% Keys are the ones already used by the project; the manuscript cites by number in',
             '% order of first citation, which elsarticle-num reproduces from \cite order.',
             '']
    problems = []
    for r in refs:
        text = r['text'].strip()
        doi = r.get('doi') or ''
        m = DOI_RE.search(text)
        if m:
            doi = m.group(1)
            text = text[:m.start()].strip()
        m = CITE_RE.match(text)
        mchap = CHAP_RE.match(text) if not m else None
        mbook = BOOK_RE.match(text) if not (m or mchap) else None
        if mchap:
            g = mchap.groupdict()
            lines.append('%% [%d] %s' % (r['n'], r.get('level', '')))
            lines.append('@incollection{%s,' % r['key'])
            lines.append('  author    = {%s},' % bib_authors(g['authors']))
            lines.append('  title     = {%s},' % texify(g['title']))
            lines.append('  booktitle = {%s},' % texify(g['booktitle']))
            lines.append('  pages     = {%s},' % g['pages'].strip())
            lines.append('  year      = {%s},' % g['year'])
            if doi:
                lines.append('  doi       = {%s},' % doi)
            lines.append('}')
            lines.append('')
            continue
        if mbook:
            g = mbook.groupdict()
            lines.append('%% [%d] %s' % (r['n'], r.get('level', '')))
            lines.append('@book{%s,' % r['key'])
            lines.append('  author    = {%s},' % bib_authors(g['authors']))
            lines.append('  title     = {%s},' % texify(g['title']))
            pub = g['publisher'].strip()
            if ', ' in pub:                       # "Springer, Solid Mechanics and Its Applications"
                pub, series = pub.split(', ', 1)
                lines.append('  publisher = {%s},' % texify(pub))
                lines.append('  series    = {%s},' % texify(series))
            else:
                lines.append('  publisher = {%s},' % texify(pub))
            lines.append('  year      = {%s},' % g['year'])
            if doi:
                lines.append('  doi       = {%s},' % doi)
            lines.append('}')
            lines.append('')
            continue
        if not m:
            parts = re.match(r'^(?P<authors>.+?)\.\s+(?P<title>.+?)\.\s+(?P<rest>.+)$', text)
            if not parts:
                problems.append((r['n'], 'unparsed', text))
                continue
            g = parts.groupdict()
            lines.append('%% WARNING ref [%d] did not match the standard pattern; '
                         'kept verbatim as @misc' % r['n'])
            lines.append('@misc{%s,' % r['key'])
            lines.append('  author    = {%s},' % bib_authors(g['authors']))
            lines.append('  title     = {%s},' % texify(g['title']))
            lines.append('  howpublished = {%s},' % texify(g['rest']))
            if doi:
                lines.append('  doi       = {%s},' % doi)
            lines.append('  note      = {Reference [%d] of the manuscript}' % r['n'])
            lines.append('}')
            lines.append('')
            continue
        g = m.groupdict()
        lines.append('%% [%d] %s' % (r['n'], r.get('level', '')))
        lines.append('@article{%s,' % r['key'])
        lines.append('  author    = {%s},' % bib_authors(g['authors']))
        lines.append('  title     = {%s},' % texify(g['title']))
        lines.append('  journal   = {%s},' % texify(g['journal']))
        lines.append('  volume    = {%s},' % g['volume'])
        if g.get('number'):
            lines.append('  number    = {%s},' % g['number'])
        lines.append('  pages     = {%s},' % g['pages'].strip())
        lines.append('  year      = {%s},' % g['year'])
        if doi:
            lines.append('  doi       = {%s},' % doi)
        lines.append('}')
        lines.append('')

    open(a.output, 'w', encoding='utf-8').write('\n'.join(lines))
    print('wrote', a.output, '-', len(refs), 'references,', len(problems), 'unparsed')
    for p in problems:
        print('   PROBLEM', p)
    return 1 if problems else 0


if __name__ == '__main__':
    sys.exit(main())
